apiVersion: v2
name: wallet
description: Microservice that handles user stats
type: application
version: 0.2.0
appVersion: 0.2.0
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
